- clean: []
- link:
    ~/.gitconfig:
      path: git/.gitconfig
      force: true
- shell:
    - command: git submodule sync --recursive
      description: Synchronize Git submodules
    - command: chsh -s /bin/zsh
      description: Change default shell to zsh
    - command: xargs -n 1 sudo pacman -S < pacman/packages
      description: Install go packages
