- clean: []
- link:
    '%USERPROFILE%\AppData\Roaming\VSCodium\User\settings.json':
      path: vscodium/settings.json
      force: true
    '%USERPROFILE%\AppData\Roaming\VSCodium':
      path: vscodium/product.json
      force: true
